/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import domen.OpstaEkranskaForma;
import java.awt.Color;
import server.Server;

/**
 *
 * @author totic
 */
public class ServerForm extends OpstaEkranskaForma {
    
    //private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ServerForm.class.getName());
    private Server server;
    /**
     * Creates new form ServerForm
     */
    public ServerForm() {
        initComponents();
        osveziStatusLabel(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pokreni = new javax.swing.JButton();
        zaustavi = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pokreni.setText("pokreni server");
        pokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pokreniActionPerformed(evt);
            }
        });

        zaustavi.setText("zaustavi server");
        zaustavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zaustaviActionPerformed(evt);
            }
        });

        statusLabel.setText("STATUS: ZAUSTAVLJEN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(zaustavi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pokreni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(80, 80, 80)
                .addComponent(statusLabel)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pokreni)
                    .addComponent(statusLabel))
                .addGap(18, 18, 18)
                .addComponent(zaustavi)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pokreniActionPerformed
        // TODO add your handling code here:
        server = new Server();
        server.setServerForm(this);
        server.start(); 

    }//GEN-LAST:event_pokreniActionPerformed

    private void zaustaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zaustaviActionPerformed
        // TODO add your handling code here:
        if(server != null){
            server.zaustavi();
        }
        osveziStatusLabel(false);
    }//GEN-LAST:event_zaustaviActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton pokreni;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JButton zaustavi;
    // End of variables declaration//GEN-END:variables

    public void osveziStatusLabel(boolean pokrenut){
        if(pokrenut){
            statusLabel.setText("STATUS: POKRENUT");
            statusLabel.setForeground(Color.green);
        }else{
            statusLabel.setText("STATUS: ZAUSTAVLJEN");
            statusLabel.setForeground(Color.red);            
        }
    }

    @Override
    protected void ocistiFormu() {
        return;
    }
}
