/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import domen.OpstaEkranskaForma;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JTextField;
import server.Server;
import util.ConfigReader;

/**
 *
 * @author totic
 */
public class ServerForm extends OpstaEkranskaForma {
    
    //private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ServerForm.class.getName());
    private Server server;
    /**
     * Creates new form ServerForm
     */
    public ServerForm() {
        super("Server");
        initComponents();
        osveziServerStatusLabel(false);
        osveziBazaKonekcijaLabel(false);
        ucitajKonfiguraciju();
        getZaustavi().setEnabled(false);
    }

    private void ucitajKonfiguraciju() {
        ConfigReader cr = new ConfigReader();
        bazaUrlField.setText(String.valueOf(cr.getProperty("db_url")));
        maxKonekcijaField.setText(String.valueOf(cr.getProperty("max_konekcija")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pokreni = new javax.swing.JButton();
        zaustavi = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        konekcijaSaBazomLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bazaUrlField = new javax.swing.JTextField();
        maxKonekcijaField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pokreni.setText("pokreni server");
        pokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pokreniActionPerformed(evt);
            }
        });

        zaustavi.setText("zaustavi server");
        zaustavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zaustaviActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(0, 2));

        jLabel1.setText("Konekcija sa bazom:");
        jPanel1.add(jLabel1);

        konekcijaSaBazomLabel.setText("POVEZAN");
        jPanel1.add(konekcijaSaBazomLabel);

        jLabel2.setText("Status servera:");
        jPanel1.add(jLabel2);

        statusLabel.setText("ZAUSTAVLJEN");
        jPanel1.add(statusLabel);

        jLabel3.setText("Baza podataka:");

        jLabel4.setText("Max konekcija:");

        bazaUrlField.setEditable(false);

        maxKonekcijaField.setEditable(false);

        jButton1.setText("konfigurisi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(zaustavi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pokreni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bazaUrlField)
                            .addComponent(maxKonekcijaField, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bazaUrlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(maxKonekcijaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pokreni)
                .addGap(18, 18, 18)
                .addComponent(zaustavi)
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pokreniActionPerformed
        // TODO add your handling code here:
        server = new Server(this);
        if(server != null){
            
            getPokreni().setEnabled(false);
            getZaustavi().setEnabled(true);
            server.start();
        }
    }//GEN-LAST:event_pokreniActionPerformed

    private void zaustaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zaustaviActionPerformed
        // TODO add your handling code here:
        if(server != null){
            
            getPokreni().setEnabled(true);
            getZaustavi().setEnabled(false);
            osveziServerStatusLabel(false);
            osveziBazaKonekcijaLabel(false);
            server.zaustavi();
        }

    }//GEN-LAST:event_zaustaviActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        otvoriKonfiguracijuButtonActionPerformed(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void otvoriKonfiguracijuButtonActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            File konfigFajl = new File("config.properties");
            if (!konfigFajl.exists()) {
                prikaziErrorPane("Konfiguracioni fajl nije pronadjen: " + konfigFajl.getAbsolutePath(), null);
                return;
            }
            if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.OPEN)) {
                Desktop.getDesktop().open(konfigFajl);
            } else {
                prikaziErrorPane("Otvaranje fajlova nije podrzano na ovom sistemu", null);
            }
        } catch (IOException ex) {
            prikaziErrorPane("Greska pri otvaranju konfiguracionog fajla", ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bazaUrlField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel konekcijaSaBazomLabel;
    private javax.swing.JTextField maxKonekcijaField;
    private javax.swing.JButton pokreni;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JButton zaustavi;
    // End of variables declaration//GEN-END:variables

    public void osveziServerStatusLabel(boolean pokrenut){
        if(pokrenut){
            statusLabel.setText("POKRENUT");
            statusLabel.setForeground(Color.green);
        }else{
            statusLabel.setText("ZAUSTAVLJEN");
            statusLabel.setForeground(Color.red);            
        }
    }
    
    public void osveziBazaKonekcijaLabel(boolean konektovan){
        if(konektovan){
            konekcijaSaBazomLabel.setText("KONEKTOVAN");
            konekcijaSaBazomLabel.setForeground(Color.green);
        }else{
            konekcijaSaBazomLabel.setText("DISKONEKTOVAN");
            konekcijaSaBazomLabel.setForeground(Color.red);
        }
    }

    @Override
    protected void ocistiFormu() {
        return;
    }

    public JTextField getBazaUrlField() {
        return bazaUrlField;
    }

    public void setBazaUrlField(JTextField bazaUrlField) {
        this.bazaUrlField = bazaUrlField;
    }

    public JTextField getMaxKonekcijaField() {
        return maxKonekcijaField;
    }

    public void setMaxKonekcijaField(JTextField maxKonekcijaField) {
        this.maxKonekcijaField = maxKonekcijaField;
    }

    public JButton getPokreni() {
        return pokreni;
    }

    public void setPokreni(JButton pokreni) {
        this.pokreni = pokreni;
    }

    public JButton getZaustavi() {
        return zaustavi;
    }

    public void setZaustavi(JButton zaustavi) {
        this.zaustavi = zaustavi;
    }
    
    
}
