/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import controller.KreirajKupacKontroler;
import controller.KreirajZahtevKontroler;
import controller.ModForme;
import controller.PretraziKupacKontroler;
import controller.PretraziZahtevKontroler;
import domen.OpstaEkranskaForma;
import domen.OpstiDomenskiObjekat;

/**
 *
 * @author totic
 */
public class MainForm extends OpstaEkranskaForma{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainForm.class.getName());

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        super();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        kreirajZahtev = new javax.swing.JMenuItem();
        pretraziZahtev = new javax.swing.JMenuItem();
        promeniZahtev = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        kreirajKupac = new javax.swing.JMenuItem();
        pretraziKupac = new javax.swing.JMenuItem();
        promeniKupac = new javax.swing.JMenuItem();
        obrisiKupac = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        ubaciProizvod = new javax.swing.JMenuItem();
        pretraziProizvod = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Zahtev za analizu");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        kreirajZahtev.setText("Kreiraj zahtev");
        kreirajZahtev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kreirajZahtevActionPerformed(evt);
            }
        });
        jMenu1.add(kreirajZahtev);

        pretraziZahtev.setText("Pretrazi zahtev");
        pretraziZahtev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pretraziZahtevActionPerformed(evt);
            }
        });
        jMenu1.add(pretraziZahtev);

        promeniZahtev.setText("Promeni zahtev");
        promeniZahtev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promeniZahtevActionPerformed(evt);
            }
        });
        jMenu1.add(promeniZahtev);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Kupac");

        kreirajKupac.setText("Kreiraj");
        kreirajKupac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kreirajKupacActionPerformed(evt);
            }
        });
        jMenu2.add(kreirajKupac);

        pretraziKupac.setText("Pretrazi");
        pretraziKupac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pretraziKupacActionPerformed(evt);
            }
        });
        jMenu2.add(pretraziKupac);

        promeniKupac.setText("Promeni");
        promeniKupac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promeniKupacActionPerformed(evt);
            }
        });
        jMenu2.add(promeniKupac);

        obrisiKupac.setText("Obrisi");
        obrisiKupac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisiKupacActionPerformed(evt);
            }
        });
        jMenu2.add(obrisiKupac);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Proizvod");

        ubaciProizvod.setText("Ubaci");
        jMenu3.add(ubaciProizvod);

        pretraziProizvod.setText("Pretrazi");
        jMenu3.add(pretraziProizvod);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

        System.out.println("KLIKNUTO");
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void kreirajZahtevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kreirajZahtevActionPerformed
        // TODO add your handling code here:
        KreirajZahtevForm f = new KreirajZahtevForm();
        KreirajZahtevKontroler k = new KreirajZahtevKontroler(f);
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }//GEN-LAST:event_kreirajZahtevActionPerformed

    private void pretraziZahtevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pretraziZahtevActionPerformed
        // TODO add your handling code here:
        PretraziZahtevForm f = new PretraziZahtevForm(false);
        PretraziZahtevKontroler k = new PretraziZahtevKontroler(f);
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }//GEN-LAST:event_pretraziZahtevActionPerformed

    private void promeniZahtevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promeniZahtevActionPerformed
        // TODO add your handling code here:
        PretraziZahtevForm f = new PretraziZahtevForm(true);
        PretraziZahtevKontroler k = new PretraziZahtevKontroler(f);
        f.setLocationRelativeTo(null);
        f.setVisible(true);        

    }//GEN-LAST:event_promeniZahtevActionPerformed

    private void promeniKupacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promeniKupacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_promeniKupacActionPerformed

    private void kreirajKupacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kreirajKupacActionPerformed
        // TODO add your handling code here:
        KreirajKupacForm f = new KreirajKupacForm();
        KreirajKupacKontroler k = new KreirajKupacKontroler(f);
        f.setLocationRelativeTo(null);
        f.setVisible(true);    
        
    }//GEN-LAST:event_kreirajKupacActionPerformed

    private void pretraziKupacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pretraziKupacActionPerformed
        // TODO add your handling code here:
        PretraziKupacForm f = new PretraziKupacForm();
        PretraziKupacKontroler k = new PretraziKupacKontroler(f, ModForme.OBICAN);
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }//GEN-LAST:event_pretraziKupacActionPerformed

    private void obrisiKupacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisiKupacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obrisiKupacActionPerformed
                                                                                                                     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem kreirajKupac;
    private javax.swing.JMenuItem kreirajZahtev;
    private javax.swing.JMenuItem obrisiKupac;
    private javax.swing.JMenuItem pretraziKupac;
    private javax.swing.JMenuItem pretraziProizvod;
    private javax.swing.JMenuItem pretraziZahtev;
    private javax.swing.JMenuItem promeniKupac;
    private javax.swing.JMenuItem promeniZahtev;
    private javax.swing.JMenuItem ubaciProizvod;
    // End of variables declaration//GEN-END:variables



    @Override
    protected void ocistiFormu() {
        
    }
}
