/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import domen.Kupac;
import domen.OpstaEkranskaForma;
import domen.Radnik;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;

/**
 *
 * @author totic
 */
public class PretraziZahtevForm extends OpstaEkranskaForma {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PretraziZahtevForm.class.getName());
    private final boolean PROMENA_DETALJA;
    
    /**
     * Creates new form PretraziZahtevForm
     */
    public PretraziZahtevForm(boolean promenaDetalja) {
        super();
        this.PROMENA_DETALJA = promenaDetalja;
        initComponents();
        if(!PROMENA_DETALJA){
            this.izmeniZahtevButton.setVisible(false);
        }
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        glavnaFormaButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaZahtevi = new javax.swing.JTable();
        pretraziButton = new javax.swing.JButton();
        detaljiButton = new javax.swing.JButton();
        kupacComboBox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        radnikComboBox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        statusCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        izmeniZahtevButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        glavnaFormaButton.setText("Glavna forma");

        tabelaZahtevi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaZahtevi);

        pretraziButton.setText("Pretraži");
        pretraziButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pretraziButtonActionPerformed(evt);
            }
        });

        detaljiButton.setText("Detalji");

        kupacComboBox.setModel(new javax.swing.DefaultComboBoxModel<Kupac>());

        jLabel13.setText("Kupac");

        radnikComboBox.setModel(new javax.swing.DefaultComboBoxModel<Radnik>());

        jLabel12.setText("Radnik");

        statusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOV", "U_OBRADI", "ZAVRSEN" }));

        jLabel4.setText("status");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Kriterijumi pretrage");

        izmeniZahtevButton.setText("Izmeni zahtev");
        izmeniZahtevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izmeniZahtevButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(glavnaFormaButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(izmeniZahtevButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(pretraziButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(detaljiButton))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(radnikComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kupacComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(182, 182, 182))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radnikComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kupacComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detaljiButton)
                    .addComponent(glavnaFormaButton)
                    .addComponent(pretraziButton)
                    .addComponent(izmeniZahtevButton))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pretraziButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pretraziButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pretraziButtonActionPerformed

    private void izmeniZahtevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izmeniZahtevButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_izmeniZahtevButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton detaljiButton;
    private javax.swing.JButton glavnaFormaButton;
    private javax.swing.JButton izmeniZahtevButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Kupac> kupacComboBox;
    private javax.swing.JButton pretraziButton;
    private javax.swing.JComboBox<Radnik> radnikComboBox;
    private javax.swing.JComboBox<String> statusCombo;
    private javax.swing.JTable tabelaZahtevi;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void ocistiFormu() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public JButton getGlavnaFormaButton() {
        return glavnaFormaButton;
    }

    public void setGlavnaFormaButton(JButton glavnaFormaButton) {
        this.glavnaFormaButton = glavnaFormaButton;
    }

    public JComboBox<Kupac> getKupacComboBox() {
        return kupacComboBox;
    }

    public void setKupacComboBox(JComboBox<Kupac> kupacComboBox) {
        this.kupacComboBox = kupacComboBox;
    }

    public JButton getPretraziButton() {
        return pretraziButton;
    }

    public void setPretraziButton(JButton pretraziButton) {
        this.pretraziButton = pretraziButton;
    }

    public JComboBox<Radnik> getRadnikComboBox() {
        return radnikComboBox;
    }

    public void setRadnikComboBox(JComboBox<Radnik> radnikComboBox) {
        this.radnikComboBox = radnikComboBox;
    }

    public JComboBox<String> getStatusCombo() {
        return statusCombo;
    }

    public void setStatusCombo(JComboBox<String> statusCombo) {
        this.statusCombo = statusCombo;
    }

    public JTable getTabelaZahtevi() {
        return tabelaZahtevi;
    }

    public void setTabelaZahtevi(JTable tabelaZahtevi) {
        this.tabelaZahtevi = tabelaZahtevi;
    }

    public JButton getDetaljiButton() {
        return detaljiButton;
    }

    public void setDetaljiButton(JButton detaljiButton) {
        this.detaljiButton = detaljiButton;
    }

    public JButton getIzmeniZahtevButton() {
        return izmeniZahtevButton;
    }

    public void setIzmeniZahtevButton(JButton izmeniZahtevButton) {
        this.izmeniZahtevButton = izmeniZahtevButton;
    }
    
    
    
}
